/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minitwitter;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import minitwitter.setUpCode.SetUp;

/**
 *
 * @author Jacob Romero
 */
// Singleton Class
public class AdminPanel extends javax.swing.JFrame {
    private static AdminPanel INSTANCE;
    
    public static AdminPanel getInstance() {
        if (INSTANCE == null) {
            synchronized (AdminPanel.class) {
                if (INSTANCE == null) {
                    INSTANCE = new AdminPanel();
                }
            }
        }
        
        return INSTANCE;
    }

    /**
     * Creates new form AdminPanel
     */
    private AdminPanel() {
        initComponents();
        
        // Custom cell rendering on the JTree to display folders only on groups in the tree
        jTree1.setCellRenderer(new DefaultTreeCellRenderer () {
            private Icon groupIcon = UIManager.getIcon("Tree.openIcon");
            @Override
            public Component getTreeCellRendererComponent(JTree tree,
                    Object value, boolean selected, boolean expanded,
                    boolean isLeaf, int row, boolean focused) {
                Component c = super.getTreeCellRendererComponent(tree, value,
                        selected, expanded, isLeaf, row, focused);
                
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;
                if (node.getUserObject().getClass().equals(User.class)) {
                    setIcon(null);
                } else if (!jTree1.isExpanded(jTree1.getSelectionPath())) {
                    setIcon(groupIcon);
                }
                return c;
            }
        });
        
        
        // Add visitors for the aggregation buttons
        VisitHandler visitor = new VisitHandler();
        messageTotalButton.addActionListener(visitor);
        userTotalButton.addActionListener(visitor);
        groupTotalButton.addActionListener(visitor);
        positivePercentButton.addActionListener(visitor);

        /***********************************************
         * Set up the users/tweets programatically
         */
        
        SetUp.run(jTree1);
         
        
        for (int i = 0; i < jTree1.getRowCount(); i++) {
            jTree1.expandRow(i);
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        addUserButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();
        userViewButton = new javax.swing.JButton();
        positivePercentButton = new javax.swing.JButton();
        messageTotalButton = new javax.swing.JButton();
        userTotalButton = new javax.swing.JButton();
        groupTotalButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        addUserTextArea = new javax.swing.JTextField();
        addGroupTextArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTree1.setModel(new TreeModel(new DefaultMutableTreeNode("Root")));
        jTree1.setCellRenderer(null);
        jScrollPane1.setViewportView(jTree1);

        addUserButton.setText("Add User");
        addUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserButtonMouseClicked(evt);
            }
        });

        addGroupButton.setText("Add Group");
        addGroupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGroupButtonMouseClicked(evt);
            }
        });

        userViewButton.setText("Open User View");
        userViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userViewButtonMouseClicked(evt);
            }
        });

        positivePercentButton.setText("Show Positive Percentage");

        messageTotalButton.setText("Show Message Total");

        userTotalButton.setText("Show User Total");

        groupTotalButton.setText("Show Total Groups");

        errorText.setForeground(new java.awt.Color(255, 0, 0));

        addUserTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addUserTextAreaKeyTyped(evt);
            }
        });

        addGroupTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addGroupTextAreaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(positivePercentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(groupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userViewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserTextArea)
                            .addComponent(addGroupTextArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(addUserTextArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(addGroupTextArea))
                        .addGap(18, 18, 18)
                        .addComponent(userViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positivePercentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Opens User Panel if the selection from the JTree is a leaf and not the root node
    private void userViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userViewButtonMouseClicked
        TreePath[] tp = jTree1.getSelectionPaths();
        
        // if there is a selection on the JTree, and we are not selecting a group then open the user view.
        if (tp != null) {
            for (TreePath t : tp) {
                if (((DefaultMutableTreeNode) t.getLastPathComponent()).isLeaf() && ((DefaultMutableTreeNode) t.getLastPathComponent()).getLevel() != 0) {
                    errorText.setText("");
                    new UserUi((User) ((DefaultMutableTreeNode)t.getLastPathComponent()).getUserObject(), (TreeModel) jTree1.getModel()).setVisible(true);
                } else {
                    errorText.setText("Selection may not be a group.");
                }
            }
        } else {
            errorText.setText("Select a user from the Tree.");
        }
    }//GEN-LAST:event_userViewButtonMouseClicked

    // Adds a group to the JTree as long as the selected item allows for having children
    private void addGroupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGroupButtonMouseClicked
        addGroup();
    }//GEN-LAST:event_addGroupButtonMouseClicked

    private void addUserTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addUserTextAreaKeyTyped
        // Allow the enter key to submit the user we want to add to the tree
        if (evt.getKeyChar() == '\n') {
            addUser();
        }
    }//GEN-LAST:event_addUserTextAreaKeyTyped

    private void addUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserButtonMouseClicked
        addUser();
    }//GEN-LAST:event_addUserButtonMouseClicked

    private void addGroupTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addGroupTextAreaKeyTyped
        // Allow the enter key to allow the group to be added to the JTree
        if (evt.getKeyChar() == '\n') {
            addGroup();
        }
    }//GEN-LAST:event_addGroupTextAreaKeyTyped

    // Adds the user into the Tree model/JTree
    private void addUser() {
        TreePath[] tp = jTree1.getSelectionPaths();
 
        // If there is a selected node on the JTree
        if (tp != null) {
            for (TreePath t : tp) {
                // And the selection is a group (i.e. we are not trying to add a user under another user.)
                // As well as the text in the text box is not only white space.
                if (((DefaultMutableTreeNode) t.getLastPathComponent()).getAllowsChildren() && !addUserTextArea.getText().trim().equals("")) {
                    ((TreeModel)jTree1.getModel()).addLeaf(t, addUserTextArea.getText().trim());
                    addUserTextArea.setText("");
                } else {
                    errorText.setText("Cannot insert empty user, or user must be inserted into a group.");
                    addUserTextArea.setText("");
                }
            }
        // In this case we are adding a node when nothing is selected. so default to the root
        } else if (!addUserTextArea.getText().trim().equals("")){
            ((TreeModel)jTree1.getModel()).addLeaf(addUserTextArea.getText());
            addUserTextArea.setText("");
        } else {
            errorText.setText("Cannot insert empty user name.");
            addUserTextArea.setText("");
        }
        
        ((DefaultTreeModel)jTree1.getModel()).reload();
        
        // Expand the node if it collapses.
        if (tp != null) {
            jTree1.expandPath(tp[tp.length - 1]);
        }
    }
    
    private void addGroup() {
        TreePath[] tp = jTree1.getSelectionPaths();
        
        // If there is a selection on the JTree
        if (tp != null) {
            for (TreePath t : tp) {
                // And the selection is a group
                // And the selection is not only white space
                if (((DefaultMutableTreeNode) t.getLastPathComponent()).getAllowsChildren() && !addGroupTextArea.getText().trim().equals("")) {
                    ((TreeModel)jTree1.getModel()).addGroup(t, addGroupTextArea.getText());
                    addGroupTextArea.setText("");
                } else {
                    errorText.setText("Cannot insert empty group, or group must be inserted into another group.");
                    addGroupTextArea.setText("");                
                }
            }
        // Otherwise no selection from the JTree has been made so defaul tot the root
        } else if (!addGroupTextArea.getText().trim().equals("")) {
            ((TreeModel) jTree1.getModel()).addGroup(addGroupTextArea.getText());
            addGroupTextArea.setText("");
        }
        ((DefaultTreeModel)jTree1.getModel()).reload();

        // expand the path of the newly created node
        if (tp != null) {
            jTree1.expandPath(tp[tp.length - 1]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            getInstance().setVisible(true);
        });
    }

    // Handeler class that will do the visiting of the specific criteria when a button is clicked
    private class VisitHandler implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            // message total button is pressed, get all the messages each user has posted
            if (e.getSource() == messageTotalButton) {
                MessageTotal mt = new MessageTotal();
                ((TreeModel) jTree1.getModel()).accept(mt);
                new DataDialog("Total messages - " + mt.getResults()).setVisible(true);
            // Group total button is pressed, get all the nodes from the tree that are of class Group
            } else if (e.getSource() == groupTotalButton) {
                GroupTotal gt = new GroupTotal();
                ((TreeModel) jTree1.getModel()).accept(gt);
                new DataDialog("Total groups - " + gt.getResults()).setVisible(true);
            // User total button is pressed, get all the nodes from the tree that are of class User
            } else if (e.getSource() == userTotalButton) {
                UserTotal ut = new UserTotal();
                ((TreeModel) jTree1.getModel()).accept(ut);
                new DataDialog("Total users - " + ut.getResults()).setVisible(true);
            // Positive Percent button is pressed, get all messages from all users that meet the criteria of a positive message.
            } else if (e.getSource() == positivePercentButton) {
                PositiveTotal pt = new PositiveTotal();
                ((TreeModel) jTree1.getModel()).accept(pt);
                new DataDialog("Total positive messages - " + pt.getResults()).setVisible(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JTextField addGroupTextArea;
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField addUserTextArea;
    private javax.swing.JLabel errorText;
    private javax.swing.JButton groupTotalButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton messageTotalButton;
    private javax.swing.JButton positivePercentButton;
    private javax.swing.JButton userTotalButton;
    private javax.swing.JButton userViewButton;
    // End of variables declaration//GEN-END:variables
}

